gnosis/olympia-interface

- src/api/restMock.js
- src/components/CurrencyName/index.js
- src/components/Header/index.js
- src/components/MarketCreateReview/index.js
- src/components/MarketCreateWizard/index.js
- src/components/MarketShortSellForm/index.js
This PR changes the default collateral Token from ETH to OLY
> PM-34 Change ETH to OLY

- package.json
- src/actions/blockchain.js
- src/api/gnosis.js
- src/components/Dashboard/Metrics/Layout.js
- src/components/Dashboard/Metrics/selector.js
- src/components/Header/header.less
- src/components/Header/index.js
- src/components/ProviderIcon/index.js
- src/components/WalletIntegrationProvider/index.js
- src/integrations/injectedWeb3.js
- src/integrations/uport/index.js
- src/middlewares/LocalStorageDump.js
- src/selectors/blockchain.js
- src/utils/helpers.js
This PR improves the UPort behavior on the app. And shows the account info on the top right-hand side of all pages updated.
> Feature PM-98 Show account info from uPort

- .eslintrc
- src/components/Dashboard/Metrics/Layout.js
- src/components/Dashboard/Metrics/Layout.stories.js
- src/components/Dashboard/Metrics/index.js
- src/components/Dashboard/Metrics/selector.js
- src/components/WalletIntegrationProvider/index.js
- src/routes/scoreboard/components/Layout.js
- src/routes/scoreboard/components/Layout.stories.js
- src/routes/scoreboard/components/ScoreTable/index.js
- src/routes/scoreboard/components/ScoreTable/index.stories.js
- src/routes/scoreboard/components/ScoreTable/table.js
- src/routes/scoreboard/containers/ScoreBoard.js
- src/routes/scoreboard/containers/actions.js
- src/routes/scoreboard/containers/selector.js
- src/routes/scoreboard/store/actions/fetchOlympiaUserData.js
- src/routes/scoreboard/store/actions/fetchOlympiaUsers.js
- src/routes/scoreboard/store/actions/index.js
- src/routes/scoreboard/store/models/user.js
- src/routes/scoreboard/store/selectors/index.js
- src/stories/knobs/scoreboardUsers.js
- src/utils/helpers.js
- webpack.dev.config.js
This PR fetches data from gnosisdb-olympia related. Scoreboard table and current user.
> Feature PM-105 feed scoreboard with data from gnosisdb

- src/components/ConnectWallet/index.js
- src/components/Dashboard/Metrics/selector.js
- src/components/WalletIntegrationProvider/index.js
- src/integrations/index.js
- src/routes/scoreboard/components/ScoreTable/table.js
- src/utils/helpers.js
This PR specifies only uPort as provider. Also fixes normalization of OLY tokens received for each user. And fixes the QR code showed twice.
> Feature PM-113 uport modal

- src/api/rest.js
- src/components/MarketList/index.js
- src/components/MarketList/marketList.less
- webpack.dev.config.js
This PR fetches markets from production whitelisted addresses and also contains fix for having the same layout on ALL pages.
> Feature PM-110 whitespace in markets

- src/components/Dashboard/Metrics/selector.js
- src/components/Header/header.less
- src/components/Header/index.js
- src/routes/scoreboard/components/ScoreTable/index.js
- src/routes/scoreboard/components/ScoreTable/table.js
This PR improves the visualization of Scoreboard table and header's account.
> Feature PM-106 update scoreboard and header

- src/components/Dashboard/index.js
- src/components/Footer/index.js
- src/components/Footer/index.stories.js
- src/components/layout/Block/index.css
- src/components/layout/Hairline/index.js
- src/components/layout/Hairline/index.stories.js
- src/components/layout/Paragraph/index.css
- src/components/layout/Paragraph/index.js
- src/routes/scoreboard/components/Layout.js
This PR includes a Hairline and Footer on Dashboard and Scoreboard views. Test included as storybook components
> Feature PM-102 add disclaimer in footer

- src/components/Dashboard/index.js
- src/components/layout/Hairline/index.js
- src/containers/App/index.js
- src/routes/scoreboard/components/Layout.js
This PR includes the footer in all pages in Olympia
> Feature PM-102 footer in all pages

- src/containers/App/index.js
- src/html/index.html
- src/middlewares/Intercom.js
- src/store.js
- webpack.dev.config.js
- webpack.prod.config.js
This PR adds integration with Intercom
> Feature PM-103 Intercom integration

- src/components/MarketBuySharesForm/index.js
This PR removes duplication of gas cost in MarketBuySharesForm
> remove gas cost duplicate

- src/components/layout/Img/index.css
- src/components/layout/Img/index.js
- src/components/layout/Paragraph/index.css
- src/components/layout/Subtitle/index.css
- src/routes/gamerules/components/LogIn/index.js
- src/routes/gamerules/components/MakePrediction/index.js
- src/routes/gamerules/components/SignUp/index.js
- src/routes/gamerules/components/index.css
This PR includes modifications in Game guide section
> Task - Improve game guide section

- src/components/ProviderIcon/index.js
- src/selectors/market.js
This PR fixes the component for sorting markets when volume attribute was selected.
> Feature PM-134 Sort markets by trading volume

- src/components/FormSelect/index.js
This PR fixes the auto reset when filtering markets
> Feature PM-146 avoid filters reset

- src/components/MarketBuySharesForm/index.js
- src/components/MarketBuySharesForm/marketBuySharesForm.less
This PR fixes the UI when buying shares avoiding change in height. Also the default text is changed to *--* in order to avoid confusion.
See video: https://drive.google.com/a/gnosis.pm/file/d/1xmvsFAwcETqnwzY2aEAUHY9pFaKBTM36/view
> PM-147 Change default text when buying tokens and fix layout when typing

- src/less/vars.less
Please also approve: https://github.com/gnosis/gnosis-management/pull/133
> Bug PM-148: Fix positioning of close button when modal uses center text

- src/components/MarketResolveForm/index.js
Please also approve: https://github.com/gnosis/gnosis-management/pull/132
> Bug PM-141: Fix Outcome Resolution

- src/components/MarketBuySharesForm/index.js
- src/components/MarketMySharesForm/index.js
- src/containers/MarketDetailPage/index.js
- src/selectors/blockchain.js
This PR adds a validator for investment. Also fixes some eslint errors
> BUG PM-142 Numbers greater than 1000 crash the app

- src/routes/gamerules/components/Layout.js
This PR adds the official Olympia video
> Adding Olympia official video

- src/actions/market.js
- src/components/OutcomePriceChanged/index.js
This PR checks if the price of an outcome has a price change higher than 5%. If so, we reject the process.
> PM-205 Check price's difference of 5%+ when selling shares

- src/components/ProgressIndicator/index.js
- src/components/Transaction/index.js
- src/components/Transactions/index.js
Backmerge of https://github.com/gnosis/gnosis-management/pull/145
> Transactions page refactoring

- src/components/MarketMySharesForm/index.js
This pr adds a check for market shares availability before initializing the form.
> Bug PM-53 Sometimes market is not loaded

- src/actions/market.js
- src/components/MarketBuySharesForm/index.js
- src/components/MarketMySharesForm/index.js
This PR adds a check for the allowance before calling gnosis.js methods. Currently the allowance is set to transaction cost everytime, so we have to approve two transactions: Approve and Buy/Sell. If the allowance is low or the same as transaction cost, it sets it to 2^256 - 1, so we have to approve only one transaction for fairly long time. I can be wrong with allowance term, but this is how I understand it and this is how its done in gnosis.js, except the value it sets allowance to.
**TEST STEPS:**
1. Find a market you never interacted with.
2. Buy shares, you'll be asked to approve an approval transaction.
3. Buy shares multiple times more, you shouldn't be asked to approve an approval transaction
> Bug PM-206 Asked for approval every transaction

- src/components/DecimalValue/index.js
- src/components/MarketMySharesForm/index.js
- src/components/MarketMyTrades/index.js
In "My tokens", the amount is rounded to two decimals, while in "My trades", it is rounded to four decimals. 
The actual amount of share is 0.0098 but it rounds it to 0
Rounded the "My tokens" amount to 4 decimals too so the user sees no disparity in numbers.
Fixed Linting for MarketMyTrades
**BUG SCREENSHOTS**:
> Bug PM-190 Shares appear as 0

- src/components/Dashboard/index.js
- src/components/MarketDetail/ExpandableViews.js
- src/components/MarketDetail/index.js
- src/router.js
This PR basically scrolls to market's My-Shares when a user clicks on SELL on any token the user has in the Dashboard view. See: [here](https://drive.google.com/a/gnosis.pm/file/d/1VtIy9CBHxrVkK50uAd_DLpNwdRQxGbn5/view?usp=sharing)
**Dev Notes**
**router.js** file is just a refactor suggested by eslint transforming the class to a functional component, also it includes a constant for a param used in the app.
> The rest of files contains changes related to this PR.
> PM-195 Scroll to market's My-Shares section from sell in dashboard

- src/integrations/uport/connector.js
- src/integrations/uport/index.js
This PR changes uPort modal text
**BEFORE:**
**AFTER:**
> PM-184 change modal text

- src/components/CurrencyName/index.js
- src/components/MarketBuySharesForm/index.js
Main changes are on line 377 in MarketBuySharesForm. Also there are linting changes for CurrencyName component
**BEFORE:** 
**AFTER:**
> BUG PM-192 show gas price in eth

- src/components/Dashboard/index.js
Suddenly we started getting this error:
Sometimes we have user's market share stored in gnosisDB but not the market itself
I added this check to prevent errors caused by it
> add a check for market existance

- src/actions/blockchain.js
- src/integrations/baseIntegration.js
- src/integrations/remote/index.js
- src/integrations/uport/index.js
- src/selectors/blockchain.js
**Test**:
Reload the page a few times, delete local storage, try again. You shouldn't get the wrong network modal anymore.
**Explanation**:
Fixed by making sure gnosis only initializes after all providers run their "updateProvider" call
> Bug PM-249: Network Modal showed briefly on load

- src/api/rest.js
- src/api/schema.js
- src/components/Dashboard/index.js
- src/config.json
- src/selectors/market.js
Also removes `market.shares` from market object - selector handles this now
> PM-295: Duplicate Share Bug Fix

- src/components/MarketBuySharesForm/index.js
- src/components/MarketMySharesForm/index.js
- src/containers/MarketDetailPage/index.js
- webpack.prod.config.js
Remove `Limit margin` field. Also trying to fix favicon in prod now showing by setting `inject: true` for `favicon-webpack-plugin` (this way it works for dev)
> PM-271 remove limit margin and fix favicon

- src/components/MarketDetail/index.js
But only if we're not looking at myShares or myTrades
> PM-275: Scroll up after change to MarketDetailPage

- src/components/MarketBuySharesForm/index.js
> Add a note for buy shares form about margin PM-271

- src/components/Footer/index.js
> PM-234 reduce space under the footer

- src/components/Dashboard/index.js
Move event listener to a container, add scrollTo after page transition from dashboard, delete unused import
> PM-266 Fix market link in "My holding" dashboard widget

- src/actions/market.js
Disable transaction explanation modals
> Feature PM-270 Disable explanation modals

- src/components/Dashboard/index.js
> PM-238: Align the words

- src/components/FormBarChartRadioButton/index.js
- src/components/MarketBuySharesForm/index.js
- src/index.js
- Set expo to 9999 in decimal.js
- Add a check for valid investment for scalar markets
> PM-307: Entering big numbers in Buy Shares form causes crash

- src/components/MarketDetail/ExpandableViews.js
- src/components/MarketDetail/index.js
- Remove unused import from MarketDetails
- Fix condition for showing resolve button
> PM-309: When countdown ends, market cannot be resolved

- src/actions/market.js
- src/components/MarketMySharesForm/index.js
> Bug PM-311: Fix Sellshares not having optimistic ui changes

- src/components/ScalarSlider/scalarSlider.less
- src/utils/constants.js
- Fix lower bound label cutting
- Fix scalar outcomes color
> PM-316, PM-315: Fix lower bound label cutting, fix scalar outcomes color

- src/components/Dashboard/index.js
- src/components/MarketMySharesForm/index.js
- src/components/MarketMyTrades/index.js
> PM-326, PM-322: Fix color match, do not show trades if market is not present

- src/components/CustomTooltip/index.js
- src/components/MarketGraph/index.js
> Bug PM-333: Graph Tooltips showing wrong values

- src/components/MarketDetail/ExpandableViews.js
- src/components/MarketMySharesForm/index.js
- src/components/MarketMySharesForm/marketMySharesForm.less
- src/components/ScalarSlider/index.js
This PR modifies the view when selling shares.
BEFORE: 
AFTER:
> PM-330 Modifications selling tokens view

- src/components/MarketBuySharesForm/index.js
- src/components/WinningOutcome/index.js
I added default value for current balance in validateInvestment methods, made a couple of refactors and additional checks for methods calculating percentage, etc. 
**TEST:**
1. Go to "Buy shares" form
2. Type unexpected values in Investment field like negative numbers, chars, numbers with chars, etc
**EXPECTED BEHAVIOUR:**
1. No errors raised in the console.
2. Interface reacts correctly to incorrect values
> Pm 343/decimal undefined

- src/components/Dashboard/index.js
- src/components/MarketList/index.js
I added labels for sorting and also deleted unused props/imports in Dashboard/MarketList component.
**BEFORE:**
**AFTER:**
> PM-346: Add labels for sorting

- src/components/Dashboard/index.js
> PM-361: Next markets -> Closing Next

- package.json
- src/components/layout/Block/index.js
- src/components/layout/Paragraph/index.css
- src/components/layout/Paragraph/index.js
- src/integrations/uport/connector.js
- src/router.js
- src/routes/terms/components/Layout.js
- src/routes/terms/containers/TermsOfUse.js
This PR has created the route terms and also the modifications for adapting the uport's login modal in order to include the terms.
> PM-367 - Introducing terms of use in uport login

- src/integrations/uport/connector.js
- src/router.js
- src/routes/terms/components/Disclaimers/index.js
- src/routes/terms/components/Eligibility/index.js
- src/routes/terms/components/ForceMajeure/index.js
- src/routes/terms/components/Gnosis/index.js
- src/routes/terms/components/HowTo/index.js
- src/routes/terms/components/Indemnity/index.js
- src/routes/terms/components/Layout.js
- src/routes/terms/components/LiabilityLimitation/index.js
- src/routes/terms/components/LicencesAccess/index.js
- src/routes/terms/components/Miscellaneous/index.js
- src/routes/terms/components/Olympia/index.js
- src/routes/terms/components/OlympiaTokens/index.js
- src/routes/terms/components/RegulatoryRisks/index.js
- src/routes/terms/components/ScopeOfTerms/index.js
- src/routes/terms/components/Termination/index.js
- src/routes/terms/components/Warranties/index.js
> Olympia Terms of Use page

- src/components/MarketGraph/index.js
> Fix graph for categorical markets

- package.json
- src/components/MarketList/index.js
> PM-378: Fix resolution date format in market list 

- src/actions/market.js
See https://github.com/gnosis/gnosis-management/pull/189 for backmerge
> Use Decimal.js to avoid sci notation string

- src/utils/helpers.js
Relies on changes merged in gnosis.js 0.7.0 RC 5
> [PM-376] Log hashes of transactions on start and sync in console

- src/components/Dashboard/index.js
> Fix columns overlap in dashboard widgets

- src/components/MarketBuySharesForm/index.js
- src/components/MarketMySharesForm/index.js
- src/utils/helpers.js
**BEFORE:**
When you type investment amount larger than 1000, scalar slider shows incorrect value
**AFTER:**
When you type investment amount larger than 1000, scalar slider shows correct value
> PM-382: Remove 1000 limit for investment value

- src/index.js
With this PR we fix decimal.js rounding problems when doing operations like selling ALL outcome tokens.
> Increasing precision in Decimal library for avoiding rounding errors

- src/components/MarketGraph/index.js
> PM-372: Change line color for scalar graphs

- src/components/Dashboard/Metrics/Layout.js
- src/components/Dashboard/dashboard.less
- src/components/DecimalValue/index.js
- src/components/Footer/index.js
- src/components/MarketBuySharesForm/index.js
- src/components/MarketList/index.js
- src/routes/scoreboard/components/ScoreTable/table.js
> PM-216: Reduce space for my tokens

- src/components/Dashboard/Metrics/Layout.js
> PM-398: Add predicted profits tooltip
