gnosis/olympia-interface

- src/components/MarketDetail/index.js
- src/components/MarketDetail/marketDetail.less
- src/components/MarketList/index.js
Also fixed three UI/UX problems:
- Page now scrolls up when entering the market details
- Indication added for "This market was resolved" and "This market was closed"
- Added Label over Resolution time, if only resolution time shows, otherwise it's confusing
> Bug PM-137: Countdown on closed/resolved market still showing

- package.json
- src/actions/blockchain.js
- src/api/gnosis.js
- src/containers/App/index.js
- src/index.js
- src/integrations/remote/index.js
- src/integrations/uport/connector.js
- src/integrations/uport/index.js
- src/middlewares/Providers.js
This PR solves the problem when the token account was reset after a fail in a transaction. Also contains commits for making the app more stable (uport related).
*  Forcing to only init wallet providers once
* Moved specific code of uport to its provider class
* Storing Uport credentials and re-using them when refreshing the page
* Checking expiration date of credentials and remove them if they are about to expire
* Removed uport's hacks before doing operations
> Feature PM-178 Delay reset data account and uport stable

- src/actions/market.js
- src/api/gnosis.js
- src/components/MarketBuySharesForm/index.js
- src/components/MarketBuySharesForm/marketBuySharesForm.less
- src/components/MarketMySharesForm/index.js
- src/containers/MarketDetailPage/index.js
- src/utils/constants.js
Quote from internal:
> If two people have buy transactions for the same outcome in the same block, one of the transactions will fail because the price for that outcome will change. We will introduce a margin (5%?) for which a market participant will be willing to pay extra for their outcome token to mitigate this issue.
> 
> This will not completely eliminate the issue since large orders can still change the price past this margin, but hopefully it will allow normal trading to happen.
> Feature: PM-151 add limit margin for buying and selling

- src/components/OutcomeCategorical/index.js
- src/components/OutcomeCategorical/outcomeCategorical.less
**BACKMERGE** https://github.com/gnosis/gnosis-management/pull/146
This PR solves:
> The resolved market "testing" shows the outcome YES 60% as a bar. We should only display the outcome name "YES" as outcome.
Before:
After:
> PM-197 > Show only winning outcome

- src/components/Dashboard/index.js
- src/components/MarketDetail/ExpandableViews.js
- src/components/MarketDetail/index.js
- src/components/MarketList/index.js
- src/components/MarketMySharesForm/index.js
- src/config.json
- src/selectors/market.js
- src/utils/helpers.js
This PR includes: 
- Adds an additional check if the market resolution date has passed to not show the countdown
- Prevent trading on markets with passed resolution date
- add `isMarketClosed` and `isMarketResolved` helpers functions so we use the same way for checking market's status in all components
- refactor components to use this helper functions
**BEFORE:**
**AFTER:**
> PM-208 Check statuses for the markets

- src/api/rest.js
So some time ago our test began to fail:
https://travis-ci.org/gnosis/olympia-interface/builds/307797319
https://travis-ci.org/gnosis/olympia-interface/builds/306830224
https://travis-ci.org/gnosis/olympia-interface/builds/307806970
It happened due to undefined whitelist environment variable, this PR fixes it + fixes eslint in api/rest.js
> Add default value for whitelist in api/rest.js + linting fixes

- src/integrations/uport/connector.js
- src/integrations/uport/index.js
- src/integrations/uport/uportNotifications.js
- src/integrations/uport/uportQr.js
This PR includes as a static property the uport's behaviour. Now we can switch from using QRCode to Push Notifications and vice-versa. 
I have followed uport's team instructions and for implementing the session management we set in the ```uport```object the following local-stored props:
_PushNotifications_
```
uport.address = cred.address
uport.pushToken = cred.pushToken
uport.publicEncKey = cred.publicEncKey
```
_QR Code scan_
```
uport.address = cred.address
```
**DevNotes**
After a conversation with UPort's team, they recommend me to set the credential's address in both ways, that broke my initial implementation. Right now, after a couple of refactors, despite the "repeated" code on the default's method on ```uportNotifications and uportQr```, I …
> PM-256 QRCode and Notifications uPort solution

- src/actions/blockchain.js
- src/api/gnosis.js
- src/components/MarketDetail/index.js
- src/components/MarketDetail/marketDetail.less
- src/containers/MarketDetailPage/index.js
- src/utils/shapes.js
This PR adds showing of gas cost for redeem winnings transaction
**BEFORE:** 
**AFTER:**
> Feature PM-257 Show gas cost for Redeeming winnings

- src/components/OutcomeScalar/index.js
**BEFORE/AFTER:**
This PR fixes adds showing winning outcome for scalar markets
> Feature PM-141 Show winning outcome on scalar markets

- src/integrations/uport/connector.js
- src/integrations/uport/uportNotifications.js
- src/integrations/uport/uportQr.js
- src/routes/scoreboard/store/actions/fetchOlympiaUserData.js
- src/routes/scoreboard/store/actions/fetchOlympiaUsers.js
This PR includes a couple of fixes for improving the uport' session management. Basically calling the method for assigning session props correctly, also in the QRCode mode I assign firstReq to false in order to avoid an extra scan
> Feature  PM-268  set uport firstreq prop session management

- src/components/ScalarSlider/index.js
- src/components/ScalarSlider/scalarSlider.less
Now looks like this:
Text overflowing is also fixed, which happened before for really long outcome unit names.
Minimum amount of Decimals added for the displayed value, so even if the value has no significant decimalplaces, it will still show atleast two so the user knows that something happened.
> PM-300: Selected/Current Trade in MarketDetail styling fixes

- src/api/gnosis.js
gnosisjs resolveEvent for some reason is not handling the unnamed parameter calling style correctly.
> A hotfix for resolve event button to work

- src/components/ScalarSlider/index.js
- src/config.json
- src/selectors/market.js
- src/selectors/marketShares.js
This PR:
- Adds `isClosed` param to share
- Now share is sellable only if market is not closed or resolved
**BEFORE:**
You can see `SELL` on a closed market in `My holdings` widget in the dashboard
**AFTER:**
You can't see `SELL` on a closed market.
> PM-339: "Sell" shows even if market is closed

- src/components/MarketDetail/marketDetail.less
- src/components/MarketGraph/index.js
- src/selectors/marketGraph.js
- src/selectors/marketTrades.js
Before:
After:
Summary of changes:
- Ordering is now fixed for Marketgraph Points (was reverse and also randomly ordered sometimes)
- Trades now always have market information, previously the API didn't return the market for marketDetailTrades, the selector now appends it
- Pointdistance between marketgraph points is now realistic to scale
> PM-358: Graphline Fixes, Trade- ordering/visibility bugfixes

- src/components/MarketMySharesForm/index.js
- src/containers/MarketDetailPage/index.js
- src/selectors/marketShares.js
Sometimes we have outcomes like this: 1, 2, 3. But in `My Tokens` tab it shows it like "2, 1". I added sorting to market shares to make sure they are in right order. Also I fixed few eslint issues in MarketDetailsPage container
> PM-364: Sort market shares to make sure they are in right order

- src/components/MarketBuySharesForm/index.js
This PR improves the buy tokens view removing the cancel button and adapting the buy button to new layout (making it bigger)
Mock's link [can be found here](https://app.zeplin.io/project/5a25459d901126c05f08a44a/screen/5a3139dc19b7f48363a8ad27)
NOW:
> PM-335 Improve buy tokens view

- src/integrations/uport/connector.js
- src/integrations/uport/index.js
- src/integrations/uport/uportQr.js
- src/selectors/blockchain.js
This PR:
- Adds a check before calling `this.getAccount()` so we know if uPort connection is initialized and not show QR code modal second time
- Set `uPort.firstReq` to true before showing login modal, so user can see download links and not only QR code
**BEFORE:**
If you click cancel on `Login` modal, QR code will show and if you close it, the website is stuck on `Connecting...`
**AFTER:**
Cancelling `Login` modal leads to the interface.
> PM-344: Cancelling the login screen

- src/containers/App/index.js
- src/index.js
- src/integrations/uport/connector.js
- src/integrations/uport/index.js
- src/integrations/uport/uportNotifications.js
- src/integrations/uport/uportQr.js
**BEFORE:**
uPort login modal is shown for not logged user on initial load. He has to close it to start browsing the interface
**AFTER:**
Modal is not shown. He can start using the interface right after the load**
> PM-366: Do not show uPort login modal for not logged user

- src/routes/scoreboard/containers/selector.js
- src/routes/scoreboard/store/selectors/index.js
This PR aligns selectors in Scoreboard and indirectly in Dashboard/Metrics components, because of **meSelector** now uses regular (and not normalized) account address. This error was a regression bug.
> PM-375 Fix scoreboard and dashboard account problem

- src/components/Dashboard/Metrics/selector.js
- src/containers/DashboardPage/index.js
- src/routes/scoreboard/containers/selector.js
- src/routes/scoreboard/store/selectors/index.js
- src/selectors/market.js
This PR is a refactor of the **Dashboard** page. I have removed unused variable ```accountPredictiveAssets``` Dashboard container and moved the  ```getAccountPredictiveAssets ``` into Dashboard/Metrics/selector.js because it was used only there (also refactored it a bit). 
NOW: 
**DevNotes**
This PR contains small changes done on PM-375, once that PR is merged I will change the scope of this one.
> PM-380 [Feature] Refactor predicted profits

- src/actions/providers.js
- src/integrations/uport/connector.js
- src/integrations/uport/index.js
This PR solves the situation when a user logs out of the app and then tries to sign in but does not scan the code. Because we previously stored manually credentials inside the uport object the app was able to recognise the user and therefore load his/her credentials anyway.
I have refactored a bit the logout process moving the code for clearing the storage to uport/connector class.
> PM-381 Fix reset credentials stored in uport

- src/containers/DashboardPage/index.js
**BEFORE:**
If you refresh the page while you're on the dashboard, you will be redirected to market list
**AFTER:**
If you refresh the page while you're on the dashboard, you won't be redirected
Actual changes are on line `12, 21, 31` other are just codestyle fixes
> BUG: Prevent redirect to market list after refresh on the dashboard

- package.json
- webpack.prod.config.js
This PR enables parallelisation and removes compression on files when running the UglifyPlugin in the prod webpack file. 
Had to do this because compilation was stuck compiling assets.
> Fix Webpack uglify speed

- package.json
- src/api/rest.js
- src/components/CustomTooltip/index.js
- src/components/MarketDetail/index.js
- src/components/MarketDetail/marketDetail.less
- src/routes/scoreboard/store/actions/fetchOlympiaUserData.js
- src/routes/scoreboard/store/actions/fetchOlympiaUsers.js
- src/selectors/marketGraph.js
- src/utils/fetch.js
- src/utils/helpers.js
Because the MarketGraph might fetch ~500 Entities from the Database, Pagination becomes an issue.
- Added new helper function called `restFetchAllPages` and `restFetchPage` to either get all pages or a specific page from REST-API urls.
- Added loading spinner for MarketGraph because loading may now take longer (previously showed empty graph, looked like a bug)
> Bug: PM-390 Pagination issue with MarketGraph

- src/middlewares/LocalStorageDump.js
**BEFORE**:
Previous transactions don't show anything after the reload of the page
**AFTER**:
Previous transactions show transactions after the reload of the page
> PM-239: Fix previous transactions not showing any

- src/actions/market.js
- src/api/rest.js
- src/components/MarketDetail/index.js
- src/utils/fetch.js
So, the problem with trades was:
If we fetch all market trades, the trade will look like the following:
```json
{  
"date":"2017-12-27T14:08:35",
"netOutcomeTokensSold":[  
"10181660606727031484142",
"9023756987006196098051"
],
"marginalPrices":[  
"0.8327",
"0.1673"
],
"outcomeToken":{  
"event":"d4adbdf647335327cf231fed7fb1407cf38b3d9f",
"index":0,
"totalSupply":"5812768581141238739979",
"address":"9c7d1e98fecf42b3038a49dd394c55d3c0a9a002"
},
"outcomeTokenCount":"11773816776166068498",
"orderType":"BUY",
"cost":"9791134810933627869",
"profit":"None",
"eventDescription":{  
"ipfsHash":"QmZHYAmaLpkJohRHgeHyXEgkrBtXzXV31yDvodQyHw3748",
"description":"How many active users will have traded (bought or sold shares) on the Olympia platform by January 1st, 2018 at 12:00 UTC? The number of users …
```
> PM-393: Fix market graph, fix trades disappearing/showing up again
